### PR TITLE
(chore): unnest navbars

### PR DESCRIPTION
**Pull request by dsinghvi**

### CODE REVIEW

**Comment by dsinghvi** [comment]
@bc-devrev @starlightknown do you mind giving this PR a review. Here's a preview URL: https://devrev-preview-7db141f3-b025-4463-aae5-64d09b6dca88.docs.buildwithfern.com

**Comment by bc-devrev** [comment]
@dsinghvi a few items:
- A reference to the landing page `/docs/pages/developer-intro` is still missing. I think it would be best as the first item at the top level, above the "About" section.
- "About the DevRev API" seems a bit verbose, especially since it turns into a URL, but I'm not sure just "About" would be adequate. In any case, please rename "API overview" to just "Overview".
- Please move the "Authentication" page to follow "Getting started", and move "Errors" to be the last item in the "About" section.
- I have a strong aversion to a category called "Advanced" because it always looks like what it is, which is an overflow bucket with random stuff. Do you have any other suggestions? If not then we can go with it but I'll aim to get rid of it as soon as possible.

**Comment by dsinghvi** [comment]
Updated preview link: https://devrev-preview-00193a0f-6dea-4205-880c-5d57f2fbc19f.docs.buildwithfern.com

**Comment by bc-devrev** [comment]
@dsinghvi because the URLs are generated from the titles rather than filepath, it looks like I have to set up a redirect rule for every page. In doing so, I found some odd tokenization: 
- "DevRev" becomes `dev-rev` as in `/snap-in-development/tutorials/using-a-snap-in-to-perform-a-dev-rev-action`
- "V1"  becomes `v-1` as in `/snap-in-development/references/snap-in-v-1-manifest`

Also, it looks like the following pages are unreferenced in the sidebar:
- `/customization`
- `/start`
- `/references/connections`
Please ensure that they are added. 

@starlightknown I don't see `/snap-ins/publish_to_marketplace` in the Fern repo, nor does it seems to be published on the current docs site. Please confirm that it's not needed.

**Comment by starlightknown** [comment]
> @starlightknown I don't see `/snap-ins/publish_to_marketplace` in the Fern repo, nor does it seems to be published on the current docs site. Please confirm that it's not needed.

@bc-devrev Asked Navneel about it, the current status is hidden, it's not published on the current site too but it's in the repo and they estimate that it can go public in 2-3 weeks.

**Comment by bc-devrev** [comment]
> also I don't think there's a `/customization` which page are you referring to?

@starlightknown I mean this one: https://docs.devrev.ai/apis/customization

> * `/start` is getting started page in snap-in tutorials which is there in sidebar.
> * `/references/connections` here I think you are referring to keyrings which is present too

Got it. @dsinghvi these items were my mistake, no action required from you.

**Comment by starlightknown** [comment]
> > also I don't think there's a `/customization` which page are you referring to?
> 
> @starlightknown I mean this one: https://docs.devrev.ai/apis/customization
> 
> > * `/start` is getting started page in snap-in tutorials which is there in sidebar.
> > * `/references/connections` here I think you are referring to keyrings which is present too
> 
> Got it. @dsinghvi these items were my mistake, no action required from you.

@bc-devrev that customization page is present in beta. You can select beta from the dropdown above on the site and you can find it there

**Pull request merged**
